### ISSUE TITLE
4.2.d Filmstrip view - css changes for positioning

### ISSUE THREAD

**Issue by loftux** [share-extras/media-viewers#21]
By adding this to viewer-common.css the toolbar is not hidden behind filmstrip overlay.

``` css
/* Overrides for filmstrip view */
.alf-filmstrip .web-preview .previewer.Embed, .alf-filmstrip .web-preview .previewer.PdfJs
{
   margin-top: 47px;
}
.alf-filmstrip-content-only .web-preview .previewer.Embed, .alf-filmstrip-content-only .web-preview .previewer.PdfJs
{
    margin-top: 1px;
}
```

The above only includes PdfJS and Embed, we might need to add for other viewers as well.
